name: Backend CI

on:
  push:
    branches:
      - 'backend'
      - 'backend/*'
      - 'backend*'
  pull_request:
    branches:
      - 'backend'
      - 'backend/*'
      - 'backend*'

jobs:
  call-backend-ci:
    uses: ./.github/workflows/reusable/backend-ci.yml
