name: Frontend CI

on:
  push:
    branches:
      - 'frontend'
      - 'frontend/*'
      - 'frontend*'

  pull_request:
    branches:
      - 'frontend'
      - 'frontend/*'
      - 'frontend*'

jobs:
  call-frontend-ci:
    uses: ./.github/workflows/reusable/frontend-ci.yml
